const ManagerScore = [
    {
        Name: 'Devon LaFrance',
        Score: 25,
        Miscellaneous: 0,
        MoneyMoney: 5,
        FindThunderTime: 6.984,
        FootbordleTime: 42.828,
        UpAndDownTHeNFLTime: 35.539,
    },
    {
        Name: 'Katie Schmidt',
        Score: 22,
        Miscellaneous: 1,
        MoneyMoney: 1,
        FindThunderTime: 8.641,
        FootbordleTime: 170.329,
        UpAndDownTHeNFLTime: 39.499,
    },
    {
        Name: 'Räley Gonzalez',
        Score: 25,
        Miscellaneous: 0,
        MoneyMoney: 7,
        FindThunderTime: 6.162,
        FootbordleTime: 68.589,
        UpAndDownTHeNFLTime: 12.131,
    },
    {
        Name: 'Jesse Ireland',
        Score: 18,
        Miscellaneous: 0,
        MoneyMoney: 4,
        FindThunderTime: 7.27,
        FootbordleTime: 584.413,
        UpAndDownTHeNFLTime: 600,
    },
    {
        Name: 'Nick LaCombe',
        Score: 13,
        Miscellaneous: -1,
        MoneyMoney: 3,
        FindThunderTime: 8.945,
        FootbordleTime: 600,
        UpAndDownTHeNFLTime: 600},
    {
        Name: 'Kyle LaCombe',
        Score: 14,
        Miscellaneous: -1,
        MoneyMoney: 6,
        FindThunderTime: 8.151,
        FootbordleTime: 600,
        UpAndDownTHeNFLTime: 53.332},
    {
        Name: 'Tyler Smith',
        Score: 18,
        Miscellaneous: 0,
        MoneyMoney: 8,
        FindThunderTime: 8.466,
        FootbordleTime: 142.996,
        UpAndDownTHeNFLTime: 24.039},
    {
        Name: 'Sabrina LaCombe',
        Score: 15,
        Miscellaneous: 1,
        MoneyMoney: 2,
        FindThunderTime: 11.203,
        FootbordleTime: 600,
        UpAndDownTHeNFLTime: 600},
]

export default ManagerScore;

