const ManagerScore = [
    {
        Name: 'Devon LaFrance',
        Score: 33,
        Miscellaneous: 0,
        MoneyMoney: 5,
        FindThunderTime: 6.984,
        FootbordleTime: 42.828,
        UpAndDownTHeNFLTime: 35.539,
        NFLMatchTime: 156.924,
        Horse: 'Broncos',
        Bet: 5,
    },
    {
        Name: 'Katie Schmidt',
        Score: 27,
        Miscellaneous: 1,
        MoneyMoney: 1,
        FindThunderTime: 8.641,
        FootbordleTime: 170.329,
        UpAndDownTHeNFLTime: 39.499,
        NFLMatchTime: 178.419,
        Horse: 'Lions',
        Bet: 2,
    },
    {
        Name: 'Räley Gonzalez',
        Score: 32,
        Miscellaneous: 0,
        MoneyMoney: 7,
        FindThunderTime: 6.162,
        FootbordleTime: 68.589,
        UpAndDownTHeNFLTime: 12.131,
        NFLMatchTime: 163.976,
        Horse: 'Bills',
        Bet: 0,
    },
    {
        Name: 'Jesse Ireland',
        Score: 24,
        Miscellaneous: 0,
        MoneyMoney: 4,
        FindThunderTime: 7.27,
        FootbordleTime: 584.413,
        UpAndDownTHeNFLTime: 600,
        NFLMatchTime: 165.806,
        Horse: 'Packers',
        Bet: 10,
    },
    {
        Name: 'Nick LaCombe',
        Score: 16,
        Miscellaneous: -1,
        MoneyMoney: 3,
        FindThunderTime: 8.945,
        FootbordleTime: 600,
        UpAndDownTHeNFLTime: 600,
        NFLMatchTime: 600,
        Horse: 'Jets',
        Bet: 16,
    },
    {
        Name: 'Kyle LaCombe',
        Score: 17,
        Miscellaneous: -1,
        MoneyMoney: 6,
        FindThunderTime: 8.151,
        FootbordleTime: 600,
        UpAndDownTHeNFLTime: 53.332,
        NFLMatchTime: 600,
        Horse: 'Bengals',
        Bet: 10,
    },
    {
        Name: 'Tyler Smith',
        Score: 22,
        Miscellaneous: 0,
        MoneyMoney: 8,
        FindThunderTime: 8.466,
        FootbordleTime: 142.996,
        UpAndDownTHeNFLTime: 24.039,
        NFLMatchTime: 428.332,
        Horse: '49ers',
        Bet: 15,
    },
    {
        Name: 'Sabrina LaCombe',
        Score: 18,
        Miscellaneous: 1,
        MoneyMoney: 2,
        FindThunderTime: 11.203,
        FootbordleTime: 600,
        UpAndDownTHeNFLTime: 600,
        NFLMatchTime: 600,
        Horse: 'Chiefs',
        Bet: 5,
    },
]

export default ManagerScore;

