const NFLPlayerList = [
    {
        Rank: 1,
        First: "Christian",
        Last: "McCaffrey",
        Position: "RB",
        Team: "49ers",
        imgUrl: "https://media.giphy.com/media/0coxd82f9ikVCGgV2m/giphy.gif",
    },
    {
        Rank: 2,
        First: "Tyreek",
        Last: "Hill",
        Position: "WR",
        Team: "Dolphins",
        imgUrl: "https://media1.giphy.com/media/7WEy6XblCPInKAITN3/giphy.gif?cid=c139f3587ofrqg1z2gdx5jd4bvpykmx582zl5cie4181fvno&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 3,
        First: "CeeDee",
        Last: "Lamb",
        Position: "WR",
        Team: "Cowboys",
        imgUrl: "https://media4.giphy.com/media/H0Tke5dk1PNpLNlpGI/giphy.gif?cid=c139f358t60tk1jiq3wfpx2933y6iefzo3l45k1q95a55ioa&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 4,
        First: "Breece",
        Last: "Hall",
        Position: "RB",
        Team: "Jets",
        imgUrl: "https://media.giphy.com/media/pWxdlCe3iLHmuatnlw/giphy.gif",
    },
    {
        Rank: 5,
        First: "Bijan",
        Last: "Robinson",
        Position: "RB",
        Team: "Falcons",
        imgUrl: "https://media.giphy.com/media/ZbA3tgNEnzG7Z8t7fM/giphy.gif",
    },
    {
        Rank: 6,
        First: "AmonRa",
        Last: "StBrown",
        Position: "WR",
        Team: "Lions",
        imgUrl: "https://media1.giphy.com/media/SOrdLBi7DMQsYJi36B/giphy.gif?cid=c139f358kran677zku6a7wodojd9ddwx71sb5d96kxgm1bdw&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 7,
        First: "JaMarr",
        Last: "Chase",
        Position: "WR",
        Team: "Bengals",
        imgUrl: "https://media4.giphy.com/media/U4vO24puxBlDXZcz39/giphy.gif?cid=c139f3580dq70ef4fxjewhccduvt23kgyzbcn6gw1r929kc0&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 8,
        First: "Justin",
        Last: "Jefferson",
        Position: "WR",
        Team: "Vikings",
        imgUrl: "https://media4.giphy.com/media/44zuwboiEZCXZD58Hv/giphy.gif?cid=c139f358vw5x15gn5h26wltvxjogu32e3envtd1exkh375nc&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 9,
        First: "AJ",
        Last: "Brown",
        Position: "WR",
        Team: "Eagles",
        imgUrl: "https://media0.giphy.com/media/Sf3k4BqkaVaTgt9DZT/giphy.gif?cid=c139f358w46dw64azg6rpx4vv64xmajd9n5yago01oe478j0&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 10,
        First: "Puka",
        Last: "Nacua",
        Position: "WR",
        Team: "Rams",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZTJ5Y240azVjMXF1Zm40dmE1dW1pZTFlN3VpaHJzaWZwcG1ubGZqbSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/DyTfyKhcsIauLIuDVu/giphy.gif",
    },
    {
        Rank: 11,
        First: "Jonathan",
        Last: "Taylor",
        Position: "RB",
        Team: "Colts",
        imgUrl: "https://media4.giphy.com/media/5XAzcO4bxq8gLoTFiT/giphy.gif?cid=c139f35846ik1ox35fw0kknevxhp9iqfj9lnb2ltpj3p5imv&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 12,
        First: "Garrett",
        Last: "Wilson",
        Position: "WR",
        Team: "Jets",
        imgUrl: "https://media4.giphy.com/media/ak8Ua6PaCBI04PV4oN/giphy.gif?cid=c139f358ozblawk26ybx6idkcmmmkz0ro8t7qnizc6f5ebuu&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 13,
        First: "Saquon",
        Last: "Barkley",
        Position: "RB",
        Team: "Eagles",
        imgUrl: "https://media4.giphy.com/media/XD9U1WTO8a3uCVCBJc/giphy.gif?cid=c139f358jwgwg1uhwcldmkm9ir3hnapzeun5mj8lvd4afx9i&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 14,
        First: "Kyren",
        Last: "Williams",
        Position: "RB",
        Team: "Rams",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbGF2ZGZhMTMxbDBobWRvbnJoMGo2NzlrdGc1NTg0aHNjdmMydGpxcCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/0ZveHJtZIwMen1QxuU/giphy.gif",
    },
    {
        Rank: 15,
        First: "Jahmyr",
        Last: "Gibbs",
        Position: "RB",
        Team: "Lions",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNHk1YnNvdGZrbTc3YWVrbDBtczFkbzdjeHI5MmsydXMxajlnOGNxcCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/PewWDWQiEWOyx7NV8m/giphy.gif",
    },
    {
        Rank: 16,
        First: "Isiah",
        Last: "Pacheco",
        Position: "RB",
        Team: "Chiefs",
        imgUrl: "https://media.giphy.com/media/XmJgdET2sOJaawczcq/giphy.gif",
    },
    {
        Rank: 17,
        First: "Derrick",
        Last: "Henry",
        Position: "RB",
        Team: "Ravens",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExejhhcnNpeGc1Z2FpMXp5Ym9pcTQydXVobWRsbDV4N3kwMXFyaXd4ZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ETevHcqlCjIesdrTFK/giphy.gif",
    },
    {
        Rank: 18,
        First: "Travis",
        Last: "Etienne",
        Position: "RB",
        Team: "Jaguars",
        imgUrl: "https://media.giphy.com/media/qTft4wKIk7bsIFMj2W/giphy.gif",
    },
    {
        Rank: 19,
        First: "Alvin",
        Last: "Kamara",
        Position: "RB",
        Team: "Saints",
        imgUrl: "https://media4.giphy.com/media/j0ZC2AJuSh0bYdfQk0/giphy.gif?cid=c139f3588jvro81x55xqrv9kj9h1rv70w6wf5up5guykc7bn&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 20,
        First: "Marvin",
        Last: "Harrison",
        Position: "RB",
        Team: "Cardinals",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcnRkZDNyMzJ1b25tZndyYjZpY2ppMTV0amUybnE0emVrMjRsZzltZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/sdxaqMXtPLfk2aQNYi/giphy.gif",
    },
    {
        Rank: 21,
        First: "Davante",
        Last: "Adams",
        Position: "WR",
        Team: "Raiders",
        imgUrl: "https://media3.giphy.com/media/QrWQMwqp5P4BUBZGNd/giphy.gif?cid=c139f358v0aew1j8al11gjoe1q8gjjohf9yzap0heb5adh1x&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 22,
        First: "Michael",
        Last: "Pittman",
        Position: "WR",
        Team: "Colts",
        imgUrl: "https://media2.giphy.com/media/HXod0sn4YzPjievVIr/giphy.gif?cid=c139f358jmlcsy2dzzdmjmz4p4ln6lsghns050pat9peom5r&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 23,
        First: "Chris",
        Last: "Olave",
        Position: "WR",
        Team: "Saints",
        imgUrl: "https://media4.giphy.com/media/CY7KQ2ykVsOkF8rFck/giphy.gif?cid=c139f358syy5zlrcnshtoyay30h8ak26pc0yiu7ewmpnox82&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 24,
        First: "Mike",
        Last: "Evans",
        Position: "WR",
        Team: "Buccaneers",
        imgUrl: "https://media1.giphy.com/media/Pg36Zrre1RJLuWId3H/giphy.gif?cid=c139f358bxhaa88a2rupk9eunga97irun4wh31bhnzpjzdys&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 25,
        First: "James",
        Last: "Cook",
        Position: "RB",
        Team: "Bills",
        imgUrl: "https://media.giphy.com/media/XNX0EcmZMBAl6lQdQr/giphy.gif",
    },
    {
        Rank: 26,
        First: "Drake",
        Last: "London",
        Position: "WR",
        Team: "Falcons",
        imgUrl: "https://media2.giphy.com/media/px9A2q8dTijytWq3TG/giphy.gif?cid=c139f358tn518vtedav8ppojs70tzoopumdxaovdsm2l7r4u&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 27,
        First: "Joe",
        Last: "Mixon",
        Position: "RB",
        Team: "Texans",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExN2xqbnRwamdzNnpteW8ycGN5d2ppaXdqbmVpMzQ3aHMyYmk4bWkydSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/yhot07RCnvLfOom1Dq/giphy.gif",
    },
    {
        Rank: 28,
        First: "Travis",
        Last: "Kelce",
        Position: "TE",
        Team: "Chiefs",
        imgUrl: "https://media3.giphy.com/media/STbT4kAqO8V9tYYMDW/giphy.gif?cid=c139f358v2hw878t4zjrnbw09fko10fdko2357upuakgo5td&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 29,
        First: "Jalen",
        Last: "Hurts",
        Position: "QB",
        Team: "Eagles",
        imgUrl: "https://media4.giphy.com/media/kntRZMXbyemNJ3Vo4N/giphy.gif?cid=c139f3586t59dy6jpg6n202lkzt4awvud5gxfbb17un85fc7&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 30,
        First: "DeVonta",
        Last: "Smith",
        Position: "WR",
        Team: "Eagles",
        imgUrl: "https://media.giphy.com/media/tXWrpyOV8w4QatyOK2/giphy.gif",
    },
    {
        Rank: 31,
        First: "Josh",
        Last: "Jacobs",
        Position: "RB",
        Team: "Packers",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExemZxZWRyb2Z6ejh5NWd1eDV1MndnNDkwbXd5dzEwZTRud2tuZnNuZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gcuZwT9mJCua57OGYJ/giphy.gif",
    },
    {
        Rank: 32,
        First: "Stefon",
        Last: "Diggs",
        Position: "WR",
        Team: "Texans",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMTZvcWxsZTQ5dGQyNjEwaWVtcXZ1bGk1MjRveWk0bGUwZmxkeW4xYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/daQ5qXKbNhM6DH6fx8/giphy.gif",
    },
    {
        Rank: 33,
        First: "Josh",
        Last: "Allen",
        Position: "QB",
        Team: "Bills",
        imgUrl: "https://media.giphy.com/media/P4ucL514BZmCq5Nmbv/giphy.gif",
    },
    {
        Rank: 34,
        First: "Sam",
        Last: "LaPorta",
        Position: "TE",
        Team: "Lions",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbWxxemk1YXBqc3hmZmZrYzNhbmU4cnk4ZHdzazJ6MWEyNTY0MmRpYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/onB2JNMIGGdTCfoG26/giphy.gif",
    },
    {
        Rank: 35,
        First: "DK",
        Last: "Metcalf",
        Position: "WR",
        Team: "Seahawks",
        imgUrl: "https://media4.giphy.com/media/8ZqdIftcqpFZU6QmXT/giphy.gif?cid=c139f358n1gmj3vgs1emfrh2my1ost2br4j3eaoi3ytg4871&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 36,
        First: "Rachaad",
        Last: "White",
        Position: "RB",
        Team: "Buccaneers",
        imgUrl: "https://media3.giphy.com/media/KciHvAgcZyIWE0Wvnt/giphy.gif?cid=c139f35814qqigztg7dka2danvj5410hu1gudtyn691ynjlq&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 37,
        First: "Kenneth",
        Last: "Walker",
        Position: "RB",
        Team: "Seahawks",
        imgUrl: "https://media.giphy.com/media/VEriTbtsLx4fY1XclP/giphy.gif",
    },
    {
        Rank: 38,
        First: "Devon",
        Last: "Achane",
        Position: "RB",
        Team: "Dolphins",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbWhoemZnaDkzcHRuYWFpZ24xNmZ6dXJhejM1ajlhbGs2cDZ1NDZtNCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/WQq6WJStvhH0QSBxVj/giphy.gif",
    },
    {
        Rank: 39,
        First: "Cooper",
        Last: "Kupp",
        Position: "WR",
        Team: "Rams",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMzdiNnNpOGJ0OTl2YnIzZTB0ZWZjc2Zobnlwd2YybjJobjljYjdsbyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xDoSf3SNQtSalPaGzO/giphy.gif",
    },
    {
        Rank: 40,
        First: "Nico",
        Last: "Collins",
        Position: "WR",
        Team: "Texans",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdW52bWltMDdhYjZ1NzVpcHJ1eHljdWkyOHQ4ZnB1MmZqdWU3MHhlaiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Ex7Ol6L3HQ7e4OPRvI/giphy.gif",
    },
    {
        Rank: 41,
        First: "Malik",
        Last: "Nabers",
        Position: "WR",
        Team: "Giants",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcGxqcnQ0anMwOGE3OWo0eG1zYjAyb2UzcWhra3o0Z3VhNjJ6cTlhdyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/WGkHGz1Kt0nKDaXlRZ/giphy.gif",
    },
    {
        Rank: 42,
        First: "Jaylen",
        Last: "Waddle",
        Position: "WR",
        Team: "Dolphins",
        imgUrl: "https://media1.giphy.com/media/9gfIGxJSzmELbBQ4oT/giphy.gif?cid=c139f358tdpvukxie1xjk00dcy07lt692au0vaxzoe2nyo49&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 43,
        First: "Mark",
        Last: "Andrews",
        Position: "TE",
        Team: "Ravens",
        imgUrl: "https://media2.giphy.com/media/uh6XvjyUHioy13xcUq/giphy.gif?cid=c139f3589idpjt9aodev7cqaiazz1oo84r4csgfdbnlbyw3u&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 44,
        First: "Anthony",
        Last: "Richardson",
        Position: "QB",
        Team: "Colts",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXpnMnBxM2Z4djZ1aWs5Yjh0eXYxYTNtaDI4bnozODF2dnUzbXg1NCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/UPmDLK9bwBd2kzIJKx/giphy.gif",
    },
    {
        Rank: 45,
        First: "Patrick",
        Last: "Mahomes",
        Position: "QB",
        Team: "Chiefs",
        imgUrl: "https://media3.giphy.com/media/vJx9UHyrRWgv9RG8lW/giphy.gif?cid=c139f358mwtd80mcacocn1l0n2vtge3j91z4rwgeud6zc64e&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 46,
        First: "Lamar",
        Last: "Jackson",
        Position: "QB",
        Team: "Ravens",
        imgUrl: "https://media2.giphy.com/media/Qw1qTKXYojfcc1sVFw/giphy.gif?cid=c139f358k92k4r1zs9t2asl9mqqfk81l9zyg03lx2f64vp6m&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 47,
        First: "Aaron",
        Last: "Jones",
        Position: "RB",
        Team: "Vikings",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExODZkbXJ4dXU0bHJiMnFhbnRhYngzeGJ0a29rd2w4ZTAwbmJmYXFqZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/USD4xJHYawRTxTILvJ/giphy.gif",
    },
    {
        Rank: 48,
        First: "Brandon",
        Last: "Aiyuk",
        Position: "WR",
        Team: "49ers",
        imgUrl: "https://media1.giphy.com/media/2yB8jMuuup6Ik2uGMP/giphy.gif?cid=c139f358vemiqfty0tok77mymiss99ubuur9wc7b8ozmgbbv&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 49,
        First: "David",
        Last: "Montgomery",
        Position: "RB",
        Team: "Lions",
        imgUrl: "https://media.giphy.com/media/C7oFS0OB6WKVMD5I0X/giphy.gif",
    },
    {
        Rank: 50,
        First: "Trey",
        Last: "McBride",
        Position: "TE",
        Team: "Cardinals",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExb3hxc25vbnZ1MHZtbDIwa3E2ZGg1d2dhazZ0cjRsemZ0aDNlcHlvMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/MaTEXRKTfGTGtN0n0k/giphy.gif",
    },
    {
        Rank: 51,
        First: "Deebo",
        Last: "Samuel",
        Position: "WR",
        Team: "49ers",
        imgUrl: "https://media1.giphy.com/media/IhsvOMPKVpvHmQ2Nzh/giphy.gif?cid=c139f358n4jyfpd2jgjj147688nyvyi1cru0lphqt350mphx&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 52,
        First: "DJ",
        Last: "Moore",
        Position: "WR",
        Team: "Bears",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDZ3am1jNXJqMHZrdms5NnoxZmxpbGVsMDBjMTJ2eWVkazVheDc2YiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/pPVg3MSZEDYLlBkKWD/giphy.gif",
    },
    {
        Rank: 53,
        First: "Zay",
        Last: "Flowers",
        Position: "WR",
        Team: "Ravens",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbXBtNHptMHBmODJ6b2o1N2lkbzYxcTNoaW1ma2VpaHM1eGRjOTc3eiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/7hzJ6FTTEmiBNwd6Vc/giphy.gif",
    },
    {
        Rank: 54,
        First: "Rhamondre",
        Last: "Stevenson",
        Position: "RB",
        Team: "Patriots",
        imgUrl: "https://media4.giphy.com/media/1LDpPBXUhpsdH1JMcZ/giphy.gif?cid=c139f358mo7sievc2cyqyudos33fdv8uxsr2g3m2xsm7f47m&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 55,
        First: "James",
        Last: "Conner",
        Position: "RB",
        Team: "Cardinals",
        imgUrl: "https://media1.giphy.com/media/8LtQTICgMv4zMDvhKN/giphy.gif?cid=c139f358g78s10oz2l82mcra37nz2aerddxmhb0hrbp5c6fd&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 56,
        First: "Joe",
        Last: "Burrow",
        Position: "QB",
        Team: "Bengals",
        imgUrl: "https://media2.giphy.com/media/6N4KzaCEtdcVohMmHS/giphy.gif?cid=c139f358cnxbg1co20f1kz5cjw12nr9ii0y3i9fvs3t4cpnt&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 57,
        First: "C.J.",
        Last: "Stroud",
        Position: "QB",
        Team: "Texans",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2s4eHhzazdpMGlwNW5yaHdpOTBvd2IwcHY3NHFpNWRuOW9pbnRsMiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/JaIicIwKiSF5GLnewF/giphy.gif",
    },
    {
        Rank: 58,
        First: "Dak",
        Last: "Prescott",
        Position: "QB",
        Team: "Cowboys",
        imgUrl: "https://media.giphy.com/media/69yK1Qwzo7MQdj8hmi/giphy.gif",
    },
    {
        Rank: 59,
        First: "Rashee",
        Last: "Rice",
        Position: "WR",
        Team: "Chiefs",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNDBxODZxOHF6bnc3NjZ0c3RkZTd5cDZnN3BmbnBpdm4xMXdxNHh0eiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/zyRpxr5jyjqQOA1oE1/giphy.gif",
    },
    {
        Rank: 60,
        First: "Calvin",
        Last: "Ridley",
        Position: "WR",
        Team: "Titans",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcGZkMjVyZTl6d2JsYm05bXVqaTJuMGFpOWgzdmVvZWl4enZmeXg1cSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/MBQM3rwieLNgBjRbjb/giphy.gif",
    },
    {
        Rank: 61,
        First: "Evan",
        Last: "Engram",
        Position: "TE",
        Team: "Jaguars",
        imgUrl: "https://media.giphy.com/media/JNifEnrr5DgNhHRyL1/giphy.gif",
    },
    {
        Rank: 62,
        First: "DAndre",
        Last: "Swift",
        Position: "RB",
        Team: "Bears",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZndnOHpiMnE3eHdyeTV1NzdpY3QzdjV1anVsOXA0cXhudXczamxqMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Tl6h3HFBxl0aloYLFk/giphy.gif",
    },
    {
        Rank: 63,
        First: "Zack",
        Last: "Moss",
        Position: "RB",
        Team: "Bengals",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnp5Ym9yZnBodmxyaTlxbGozOXNycmE3djVueWZwcXh2OXM3OGt3OSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/k4RCtkyj8EIoqv5WKL/giphy.gif",
    },
    {
        Rank: 64,
        First: "Tee",
        Last: "Higgins",
        Position: "WR",
        Team: "Bengals",
        imgUrl: "https://media1.giphy.com/media/LBFj8nCTE445ZCdL9k/giphy.gif?cid=c139f358kox9q6d5bt3ithbjpetiwemegyjjp6kx3c4zpgbh&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 65,
        First: "Javonte",
        Last: "Williams",
        Position: "RB",
        Team: "Broncos",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExaTR4ZnZoa3JlY3c2dnd6aXNkNDN6dHNkenp1N2d0bHloeDg4dndxbiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/z6UaLNFTKRzIQykzOi/giphy.gif",
    },
    {
        Rank: 66,
        First: "Christian",
        Last: "Kirk",
        Position: "WR",
        Team: "Jaguars",
        imgUrl: "https://media.giphy.com/media/w6Qe1LvwXXULQBYDyh/giphy.gif",
    },
    {
        Rank: 67,
        First: "Dalton",
        Last: "Kincaid",
        Position: "TE",
        Team: "Bills",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExeThwMWUwNDJ5cXhoa3VvaXJiMWZ2bjRmaXZlb3oxempqbXprbHJqZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/vyJDeYb44zV1vQj9nD/giphy-downsized-large.gif",
    },
    {
        Rank: 68,
        First: "David",
        Last: "Njoku",
        Position: "TE",
        Team: "Browns",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExY255Y3Jjc3l6b29neGtoaXczNTdzenA0a3k4a3kyYW85a295dmJzeCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3ohhwv7ECyvHRqDWkU/giphy.gif",
    },
    {
        Rank: 69,
        First: "Jordan",
        Last: "Love",
        Position: "QB",
        Team: "Packers",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2pmZTJxMzJ6ZTZndXZya3J0NXB5ZTA5eTJuM3A1dzk0bW9odXpwbSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/nZL6QWXW1VZ9XAgfGd/giphy.gif",
    },
    {
        Rank: 70,
        First: "Brock",
        Last: "Purdy",
        Position: "QB",
        Team: "49ers",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMndueWxpbm1zcGY5d3R0M2txYjVzNzBiN2V3dGhod3NyNXhoY2gxMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/923VK7XDOy88oWDkgn/giphy.gif",
    },
    {
        Rank: 71,
        First: "Kyler",
        Last: "Murray",
        Position: "QB",
        Team: "Cardinals",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExamxjbm1xdG9lZjluZXl1ZXNsZ3g2eDB3bndrdzg4YWswYnp6bDdlMyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gMdzIi12zCz4rVRl5Y/giphy.gif",
    },
    {
        Rank: 72,
        First: "George",
        Last: "Kittle",
        Position: "TE",
        Team: "49ers",
        imgUrl: "https://media2.giphy.com/media/z89e1rdAKA2SFbmRtf/giphy.gif?cid=c139f3581h222thltqw3ze24u0nxauvogw13xk0b8pyefrdz&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 73,
        First: "Raheem",
        Last: "Mostert",
        Position: "RB",
        Team: "Dolphins",
        imgUrl: "https://media.giphy.com/media/wkgwSzduqPGujfKqy5/giphy.gif",
    },
    {
        Rank: 74,
        First: "Chris",
        Last: "Godwin",
        Position: "WR",
        Team: "Buccaneers",
        imgUrl: "https://media1.giphy.com/media/jmqUR41Z74eKdD82ut/giphy.gif?cid=c139f3580budu8f48e7xmkh2hl1r1ocysz5o79q64jttb1yp&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 75,
        First: "George",
        Last: "Pickens",
        Position: "WR",
        Team: "Steelers",
        imgUrl: "https://media2.giphy.com/media/agQTW8bMU4QFBqUTsX/giphy.gif?cid=c139f3584dd1ua4os9giv0k0vz0x8jksc1xkqpr7d65kag5i&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 76,
        First: "Zamir",
        Last: "White",
        Position: "RB",
        Team: "Raiders",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOXVtNTI5OWkzOWo2cmpwazI5dmxjdzBheWlpemFyb20wMGdkaG00ZSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/6Spg4HyZpmBONWgfac/giphy.gif",
    },
    {
        Rank: 77,
        First: "Amari",
        Last: "Cooper",
        Position: "WR",
        Team: "Browns",
        imgUrl: "https://media2.giphy.com/media/YWZKLAQhM9Zy79lDkA/giphy.gif?cid=c139f358ot24wrhxahxlbfeovihqp9xitd1yeya8snslgp1i&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 78,
        First: "Keenan",
        Last: "Allen",
        Position: "WR",
        Team: "Bears",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOWNvemg5OTM3enJjdmlrZmE1bjk1bnk0cWoxZ25rNzMzbm5lZnZkdiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/XKBR7uZX18sYBKJSNS/giphy.gif",
    },
    {
        Rank: 79,
        First: "Diontae",
        Last: "Johnson",
        Position: "WR",
        Team: "Panthers",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExYWN3d3Fpbjkzd3hlZGs1cWhkczIxd2xpZjUwcXlmeHZramtrOWxrNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Nr1BtyosWT5AXQbAMX/giphy.gif",
    },
    {
        Rank: 80,
        First: "Tank",
        Last: "Dell",
        Position: "WR",
        Team: "Texans",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdGQ1djVxd250cTRweWl2Z2s0bXRhYWdiM2VkZ2x2eDd6aWV4N3hoZiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/XtOTlCljiHHxfobh32/giphy.gif",
    },
    {
        Rank: 81,
        First: "Brian",
        Last: "Robinson",
        Position: "RB",
        Team: "Commanders",
        imgUrl: "https://media.giphy.com/media/PiuRqy03lYzgiB3NDi/giphy.gif",
    },
    {
        Rank: 82,
        First: "Austin",
        Last: "Ekeler",
        Position: "RB",
        Team: "Commanders",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZnJleDhiOXAxMXVjOTc0amxqMGphMWUwOHd4d2duNHo1czh5bncwYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BZl10YHWDXAFuWTQul/giphy.gif",
    },
    {
        Rank: 83,
        First: "DeAndre",
        Last: "Hopkins",
        Position: "WR",
        Team: "Titans",
        imgUrl: "https://media4.giphy.com/media/iJIelaTabJy39JXJgf/giphy.gif?cid=c139f358759eriaabhma00st3b9f14czdrx5sw7qjwy18i37&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 84,
        First: "Terry",
        Last: "McLaurin",
        Position: "WR",
        Team: "Commanders",
        imgUrl: "https://media2.giphy.com/media/zKSu7yxpD4HWQviSrf/giphy.gif?cid=c139f358pfdi3otocffkoqemqte7fdt9vgjvtn28ugw2agbu&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 85,
        First: "Courtland",
        Last: "Sutton",
        Position: "WR",
        Team: "Broncos",
        imgUrl: "https://media3.giphy.com/media/8ylJVPiTchFdl2Lm4g/giphy.gif?cid=c139f3583o8nv4ylhh1iskrucpfeheuj84b037od5o657fud&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 86,
        First: "TJ",
        Last: "Hockenson",
        Position: "TE",
        Team: "Vikings",
        imgUrl: "https://media1.giphy.com/media/fr5oMivPtHeUCQM8n8/giphy.gif?cid=c139f358gh6rk7856eox1xllo7edw0oo0lew24wuopt6rl9v&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 87,
        First: "Jaylen",
        Last: "Warren",
        Position: "RB",
        Team: "Steelers",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNWluZmZzNW9xN3o5eW81MTI0d3A1Z3FlaHl4bTZrM21yYWJnaHppaCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/tkU4HX4ZifN1FmPled/giphy.gif",
    },
    {
        Rank: 88,
        First: "Najee",
        Last: "Harris",
        Position: "RB",
        Team: "Steelers",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdjFoc2Z0b3d1dWJqNWJycmhsdTd6aG1jYjk2cGVhaHRvNzVucDU3ciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/F5TExytDCA9PdG6qYS/giphy.gif",
    },
    {
        Rank: 89,
        First: "Jordan",
        Last: "Addison",
        Position: "WR",
        Team: "Vikings",
        imgUrl: "https://media1.giphy.com/media/uAqX2S5qQjZqpv3hyu/giphy.gif?cid=c139f358bd7e6a5tqup0nk35l3c5jojaj7af613h70eithi9&ep=v1_gifs_search&rid=giphy.gif&ct=g",
    },
    {
        Rank: 90,
        First: "Christian",
        Last: "Watson",
        Position: "WR",
        Team: "Packers",
        imgUrl: "https://media.giphy.com/media/CAs0Nu30WvsVlmu8BJ/giphy.gif",
    },
    {
        Rank: 91,
        First: "Jayden",
        Last: "Daniels",
        Position: "QB",
        Team: "Commanders",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ3NucmxweHBqMXA2enJ3cjNraTlyNnJpNXBrOXNrOWswczY4dmJtMCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/5lPF7xxWTRCJwvnU9O/giphy.gif",
    },
    {
        Rank: 92,
        First: "Tyjae",
        Last: "Spears",
        Position: "RB",
        Team: "Titans",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExY3UxZ2J3eXd4amVkb2sweWdidmFtYnRpaTR4dnEybmxodDg4M3lxYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/sZpgeKHXP428fYsHpr/giphy.gif",
    },
    {
        Rank: 93,
        First: "Jonathon",
        Last: "Brooks",
        Position: "RB",
        Team: "Panthers",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZjVzNDZ0NXlzYmNiaW9oN3JqaW95ZjhibW5kczU4YXJ4YjFnNjh1bCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/KmpZQWMxKRGAbvHV0S/giphy.gif",
    },
    {
        Rank: 94,
        First: "Jake",
        Last: "Ferguson",
        Position: "TE",
        Team: "Cowboys",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExcHMxdnZzYWI3MWFqZG91d3lmMG40ZHY1am14anFnYWc4YzN2YXgycyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gZL0SQtoKLkTO9JP8c/giphy.gif",
    },
    {
        Rank: 95,
        First: "Tony",
        Last: "Pollard",
        Position: "RB",
        Team: "Titans",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZHBkcnJ1aHh1aXEwYXY2eHp6aHZjcmtvN3ptc2VjZ2w2MmcxZWw3ayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ei9FZ5r9x90v2ckvUN/giphy.gif",
    },
    {
        Rank: 96,
        First: "Devin",
        Last: "Singletary",
        Position: "RB",
        Team: "Giants",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExbzRlMmlwaWRmZHllc213OGc1OW40cnVkNWY5ZjFvYTd6d2RtbWJpayZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NiK9AkQTwyXowJeONw/giphy.gif",
    },
    {
        Rank: 97,
        First: "Jayden",
        Last: "Reed",
        Position: "WR",
        Team: "Packers",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXRlNmI2OWJubjIxbW1lNjBjZWJrZ3RnaXRrZ3R3bXhqcDN6c2Q5dCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/r0FVtF0zVXCjJBdYSE/giphy.gif",
    },
    {
        Rank: 98,
        First: "Ladd",
        Last: "McConkey",
        Position: "WR",
        Team: "Chargers",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExdmVrcnE5bXdoMDYwbXpzZGZtNGpnd3VycnpvaTIyZDhibjhzZndwYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/TS4ddb7hN2Uku2p8je/giphy.gif",
    },
    {
        Rank: 99,
        First: "Ezekiel",
        Last: "Elliot",
        Position: "RB",
        Team: "Cowboys",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExc2J2ZnhoOHBkdGxnZzNieG53cDl3ZnBxZW4ybTd4ZDRudzlrb2x0dCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/xT9IgshPNRlnHtJKBa/giphy.gif",
    },
    {
        Rank: 100,
        First: "Mike",
        Last: "Williams",
        Position: "WR",
        Team: "Jets",
        imgUrl: "https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExOHp5ejY1OWVrdm10enh5ZTk5aXBzeWcxYTgxMmhremd2NWQ4N2JuYiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3o7aDbIXC500bq0vCg/giphy.gif",
    },
]

export default NFLPlayerList;

